apiVersion: v1
kind: Service
metadata:
  name: beancs-controller
  namespace: beancs-system
  labels:
    app: beancs-controller
    managed-by: beancs
spec:
  selector:
    app: beancs-controller
  ports:
    - name: http
      port: 8080
      targetPort: http
